[CmdletBinding()]
param([Parameter(Position=0)][ValidateSet('explain','doctor')][string]$Command='explain',[string]$UserPrincipalName,[string]$OutputPath=(Join-Path $PWD ('s8-access-explainer-'+(Get-Date -Format 'yyyyMMdd-HHmmss'))),[switch]$InstallDependencies)
$modulePath=Join-Path $PSScriptRoot 'S8.M365.psm1';if(-not(Test-Path $modulePath)){$modulePath=Join-Path (Split-Path $PSScriptRoot) '_shared\S8.M365.psm1'};Import-Module $modulePath -Force;Initialize-S8Runtime
if($Command-eq'doctor'){[pscustomobject]@{PowerShell=$PSVersionTable.PSVersion.ToString();GraphModule=[bool](Get-Module -ListAvailable Microsoft.Graph.Authentication);OutputPath=$OutputPath}|Format-List;exit};if(-not$UserPrincipalName){throw 'explain requires -UserPrincipalName.'}
$evidence=New-Object System.Collections.ArrayList;$context=Connect-S8Graph @('User.Read.All','Group.Read.All','Directory.Read.All','Application.Read.All','LicenseAssignment.Read.All') -InstallDependencies:$InstallDependencies;$escaped=[uri]::EscapeDataString($UserPrincipalName)
$user=@(Invoke-S8Collection 'User' {Get-S8GraphCollection "https://graph.microsoft.com/v1.0/users/$escaped?`$select=id,displayName,userPrincipalName,accountEnabled,userType,createdDateTime,onPremisesSyncEnabled"} $evidence)|Select-Object -First 1;if(-not$user){throw "User not found or unreadable: $UserPrincipalName"}
$id=$user.id;$memberships=Invoke-S8Collection 'Transitive memberships' {Get-S8GraphCollection "https://graph.microsoft.com/v1.0/users/$id/transitiveMemberOf?`$select=id,displayName,description,groupTypes,securityEnabled,mailEnabled"} $evidence;$apps=Invoke-S8Collection 'Application role assignments' {Get-S8GraphCollection "https://graph.microsoft.com/v1.0/users/$id/appRoleAssignments"} $evidence;$owned=Invoke-S8Collection 'Owned directory objects' {Get-S8GraphCollection "https://graph.microsoft.com/v1.0/users/$id/ownedObjects?`$select=id,displayName,appId,groupTypes"} $evidence;$licenses=Invoke-S8Collection 'License details' {Get-S8GraphCollection "https://graph.microsoft.com/v1.0/users/$id/licenseDetails"} $evidence
$rows=@();foreach($x in $memberships){$rows+=[pscustomobject]@{AccessType='TransitiveMembership';Resource=$x.displayName;ResourceId=$x.id;GrantedThrough='Direct or nested directory membership';Detail=$x.'@odata.type'}};foreach($x in $apps){$rows+=[pscustomobject]@{AccessType='ApplicationRole';Resource=$x.resourceDisplayName;ResourceId=$x.resourceId;GrantedThrough=if($x.principalType-eq'Group'){'Group assignment'}else{'Direct user assignment'};Detail=$x.appRoleId}};foreach($x in $owned){$rows+=[pscustomobject]@{AccessType='Ownership';Resource=$x.displayName;ResourceId=$x.id;GrantedThrough='Directory object ownership';Detail=$x.'@odata.type'}};foreach($x in $licenses){$rows+=[pscustomobject]@{AccessType='LicenseEntitlement';Resource=$x.skuPartNumber;ResourceId=$x.skuId;GrantedThrough='Direct or group-based licensing';Detail=(@($x.servicePlans|Where-Object provisioningStatus-eq'Success'|ForEach-Object servicePlanName)-join';')}}
New-Item -ItemType Directory $OutputPath -Force|Out-Null;Export-S8Data $OutputPath 'identity-summary' @($user);Export-S8Data $OutputPath 'access-paths' $rows;Export-S8Data $OutputPath 'raw-memberships' $memberships;Export-S8Data $OutputPath 'raw-app-role-assignments' $apps;Complete-S8Run $OutputPath 'm365-access-explainer' $Command $context $evidence;Write-S8Report $OutputPath 'System 8 · M365 Access Explainer' ([ordered]@{'Identity'=@($user);'Access paths'=$rows;'Collection evidence'=@($evidence)})
[pscustomobject]@{Output=$OutputPath;Identity=$UserPrincipalName;AccessPaths=$rows.Count;Mode='Read-only identity access explanation'}|Format-List
