[CmdletBinding()]param([Parameter(Position=0)][ValidateSet('full','analyze','users','skus','savings','doctor','help')][string]$Command='full',[string]$OutputPath=(Join-Path $PWD ('s8-license-optimizer-'+(Get-Date -Format 'yyyyMMdd-HHmmss'))),[string]$PriceFile,[int]$DormantDays=90,[string]$FixturePath,[switch]$InstallDependencies)
Import-Module (Join-Path $PSScriptRoot 'S8.M365.psm1') -Force;Initialize-S8Runtime
if($Command-eq'help'){Write-Output 's8license full|analyze|users|skus|savings|doctor [-FixturePath fixture.json] [-PriceFile prices.csv] [-DormantDays 90]';exit}
if($Command-eq'doctor'){[pscustomobject]@{PowerShell=$PSVersionTable.PSVersion.ToString();GraphModule=[bool](Get-Module -ListAvailable Microsoft.Graph.Authentication);Fixture=[bool]$FixturePath}|Format-List;exit}
$ev=New-Object Collections.ArrayList;$ctx=if($FixturePath){[pscustomobject]@{TenantId='fixture';Account='offline'}}else{Connect-S8Graph @('User.Read.All','Organization.Read.All','AuditLog.Read.All','Directory.Read.All') -InstallDependencies:$InstallDependencies}
$skus=Invoke-S8SourceCollection 'Subscribed SKUs' 'subscribedSkus' $FixturePath {Get-S8GraphCollection 'https://graph.microsoft.com/v1.0/subscribedSkus'} $ev
$users=Invoke-S8SourceCollection 'Users' 'users' $FixturePath {Get-S8GraphCollection 'https://graph.microsoft.com/beta/users?$select=id,displayName,userPrincipalName,accountEnabled,userType,assignedLicenses,signInActivity,createdDateTime'} $ev
$prices=@{};if($PriceFile){Import-Csv $PriceFile|%{$prices[$_.SkuPartNumber]=[decimal]$_.MonthlyUnitPrice}};$skuMap=@{};foreach($s in $skus){$skuMap[[string]$s.skuId]=$s.skuPartNumber}
$userRows=@($users|%{$last=$_.signInActivity.lastSuccessfulSignInDateTime;if(-not$last){$last=$_.signInActivity.lastSignInDateTime};$names=@($_.assignedLicenses|%{$skuMap[[string]$_.skuId]});$days=if($last){[math]::Floor(((Get-Date)-[datetime]$last).TotalDays)}else{$null};[pscustomobject]@{DisplayName=$_.displayName;UPN=$_.userPrincipalName;Enabled=$_.accountEnabled;LastSignIn=$last;DaysSinceSignIn=$days;Licenses=($names-join';');CandidateReason=if(-not$_.accountEnabled-and$names.Count){'Disabled licensed account'}elseif($names.Count-and((-not$last)-or$days-ge$DormantDays)){'Dormant licensed account'}else{''}}})
$skuRows=@($skus|%{[pscustomobject]@{SkuPartNumber=$_.skuPartNumber;Enabled=$_.prepaidUnits.enabled;Consumed=$_.consumedUnits;Available=([int]$_.prepaidUnits.enabled-[int]$_.consumedUnits);UtilizationPct=if($_.prepaidUnits.enabled){[math]::Round(100*[int]$_.consumedUnits/[int]$_.prepaidUnits.enabled,1)}else{0}}});$candidates=@($userRows|? CandidateReason);$savings=@($candidates|%{$monthly=0;foreach($n in @($_.Licenses-split';')){if($prices.ContainsKey($n)){$monthly+=$prices[$n]}};[pscustomobject]@{UPN=$_.UPN;Reason=$_.CandidateReason;Licenses=$_.Licenses;EstimatedMonthlySavings=$monthly;EstimatedAnnualSavings=12*$monthly;PricingStatus=if($PriceFile){'Customer supplied'}else{'Not calculated'}}})
New-Item -ItemType Directory $OutputPath -Force|Out-Null;Export-S8Data $OutputPath 'sku-utilization' $skuRows;Export-S8Data $OutputPath 'user-license-posture' $userRows;Export-S8Data $OutputPath 'optimization-candidates' $candidates;Export-S8Data $OutputPath 'estimated-savings' $savings;Complete-S8Run $OutputPath 'm365-license-optimizer' $Command $ctx $ev $(if($FixturePath){'Offline fixture'}else{'Live Graph'});Write-S8Report $OutputPath 'System 8 · M365 License Optimizer' ([ordered]@{'SKU utilization'=$skuRows;'Candidates'=$candidates;'Savings'=$savings;'Evidence'=@($ev)});[pscustomobject]@{Output=$OutputPath;Candidates=$candidates.Count;Mode='Read-only'}
