[CmdletBinding()]
param([Parameter(Position=0)][ValidateSet('assess','sites','licenses','pilot','full','doctor')][string]$Command='full',[string]$OutputPath=(Join-Path $PWD ('s8-copilot-readiness-'+(Get-Date -Format 'yyyyMMdd-HHmmss'))),[int]$StaleDays=365,[switch]$InstallDependencies)
$modulePath=Join-Path $PSScriptRoot 'S8.M365.psm1';if(-not(Test-Path $modulePath)){$modulePath=Join-Path (Split-Path $PSScriptRoot) '_shared\S8.M365.psm1'};Import-Module $modulePath -Force;Initialize-S8Runtime
if($Command-eq'doctor'){[pscustomobject]@{PowerShell=$PSVersionTable.PSVersion.ToString();GraphModule=[bool](Get-Module -ListAvailable Microsoft.Graph.Authentication);StaleDays=$StaleDays;OutputPath=$OutputPath}|Format-List;exit}
$evidence=New-Object System.Collections.ArrayList;$context=Connect-S8Graph @('Sites.Read.All','User.Read.All','Group.Read.All','Directory.Read.All','InformationProtectionPolicy.Read.All') -InstallDependencies:$InstallDependencies
$skus=Invoke-S8Collection 'Subscribed SKUs' {Get-S8GraphCollection 'https://graph.microsoft.com/v1.0/subscribedSkus'} $evidence;$users=Invoke-S8Collection 'Users and assigned plans' {Get-S8GraphCollection 'https://graph.microsoft.com/v1.0/users?$select=id,displayName,userPrincipalName,accountEnabled,userType,assignedLicenses,assignedPlans'} $evidence;$sites=Invoke-S8Collection 'SharePoint sites' {Get-S8GraphCollection 'https://graph.microsoft.com/v1.0/sites?search=*&$select=id,displayName,webUrl,createdDateTime,lastModifiedDateTime'} $evidence;$groups=Invoke-S8Collection 'Microsoft 365 groups' {Get-S8GraphCollection 'https://graph.microsoft.com/v1.0/groups?$select=id,displayName,visibility,groupTypes,resourceProvisioningOptions'} $evidence;$guests=@($users|Where-Object userType-eq'Guest')
$planMap=@{};foreach($sku in $skus){foreach($plan in @($sku.servicePlans)){$planMap[[string]$plan.servicePlanId]=$plan.servicePlanName}}
$licenseRows=@($users|Where-Object{$_.accountEnabled-and$_.userType-eq'Member'}|ForEach-Object{$plans=@($_.assignedPlans|Where-Object capabilityStatus-eq'Enabled'|ForEach-Object{$planMap[[string]$_.servicePlanId]});[pscustomobject]@{UPN=$_.userPrincipalName;DisplayName=$_.displayName;CopilotPlan=[bool](@($plans|Where-Object{$_-match'COPILOT'}).Count);EnabledPlans=($plans-join';')}})
$siteRows=@($sites|ForEach-Object{$days=if($_.lastModifiedDateTime){[math]::Floor(((Get-Date)-[datetime]$_.lastModifiedDateTime).TotalDays)}else{$null};$matching=@($groups|Where-Object displayName-eq$_.displayName|Select-Object -First 1);$visibility=if($matching){$matching[0].visibility}else{'Unknown'};$signals=@();if($days-ge$StaleDays){$signals+='Stale content'};if($visibility-eq'Public'){$signals+='Public group-connected site'};if($_.webUrl-match'-my\.sharepoint\.com/personal/'){$signals+='Personal site'};[pscustomobject]@{Site=$_.displayName;Url=$_.webUrl;Modified=$_.lastModifiedDateTime;DaysSinceModified=$days;Visibility=$visibility;RiskSignals=($signals-join';');RiskScore=[math]::Min(100,($(if($days-ge$StaleDays){35}else{0})+$(if($visibility-eq'Public'){35}else{0})+$(if($_.webUrl-match'/personal/'){10}else{0})));EvidenceLimit='Graph site inventory does not enumerate all sharing links or item permissions'}}|Sort-Object RiskScore -Descending)
$findings=@([pscustomobject]@{Gate='Licensed pilot cohort';Status=if(@($licenseRows|Where-Object CopilotPlan).Count){'Pass'}else{'Review'};Evidence="$(@($licenseRows|Where-Object CopilotPlan).Count) enabled users with a COPILOT service plan";Action='Confirm pilot personas, prerequisite licensing and assignment'},[pscustomobject]@{Gate='Content lifecycle';Status=if(@($siteRows|Where-Object{$_.DaysSinceModified-ge$StaleDays}).Count){'Review'}else{'Pass'};Evidence="$(@($siteRows|Where-Object{$_.DaysSinceModified-ge$StaleDays}).Count) stale sites";Action='Confirm ownership, archive or exclude obsolete content'},[pscustomobject]@{Gate='Broad collaboration';Status=if(@($siteRows|Where-Object Visibility-eq'Public').Count){'Review'}else{'Pass'};Evidence="$(@($siteRows|Where-Object Visibility-eq'Public').Count) public group-connected sites; $($guests.Count) guest identities";Action='Run SharePoint Data Access Governance and permission-state reviews'},[pscustomobject]@{Gate='Permission-depth evidence';Status='ManualEvidenceRequired';Evidence='Generic Graph inventory cannot prove all sharing links, broken inheritance, Everyone claims or sensitive item exposure';Action='Export SharePoint Advanced Management/Purview evidence before production rollout'})
$pilot=@($licenseRows|Where-Object CopilotPlan|Select-Object UPN,DisplayName,@{n='PilotDecision';e={'Candidate - validate role, training and data access'}},@{n='ChangeMode';e={'Plan only'}})
New-Item -ItemType Directory $OutputPath -Force|Out-Null;Export-S8Data $OutputPath 'readiness-gates' $findings;Export-S8Data $OutputPath 'site-risk-register' $siteRows;Export-S8Data $OutputPath 'license-readiness' $licenseRows;Export-S8Data $OutputPath 'pilot-candidates' $pilot;Complete-S8Run $OutputPath 'm365-copilot-readiness' $Command $context $evidence;Write-S8Report $OutputPath 'System 8 · M365 Copilot Readiness' ([ordered]@{'Readiness gates'=$findings;'Site risk register'=$siteRows;'Pilot candidates'=$pilot;'License readiness'=$licenseRows;'Collection evidence'=@($evidence)})
[pscustomobject]@{Output=$OutputPath;Sites=$siteRows.Count;RiskSites=@($siteRows|Where-Object RiskScore-gt0).Count;LicensedCandidates=$pilot.Count;Mode='Read-only pilot planning'}|Format-List
