$ErrorActionPreference='Stop'
$repo=Split-Path $PSScriptRoot
$errors=@();Get-ChildItem $repo -Recurse -Include *.ps1,*.psm1|ForEach-Object{$tokens=$null;$parse=$null;[void][Management.Automation.Language.Parser]::ParseFile($_.FullName,[ref]$tokens,[ref]$parse);if($parse){$errors+=$parse|ForEach-Object{"$($_.Extent.File):$($_.Extent.StartLineNumber): $($_.Message)"}}};if($errors){$errors|ForEach-Object{Write-Error $_};throw "Syntax errors: $($errors.Count)"};Write-Host 'SYNTAX_OK'
$manifest=Get-Content (Join-Path $repo 'tools/s8/manifests/stable.json') -Raw|ConvertFrom-Json;$targets=@('m365-license-optimizer','m365-tenant-diff','m365-sharepoint-modernizer','m365-security-baseline','m365-migration-estimator');foreach($n in $targets){$p=@($manifest.packages|Where-Object name-eq$n);if($p.Count-ne1){throw "Manifest missing $n"};$rel=$p[0].installScript-replace'^system8-main/','';if(-not(Test-Path (Join-Path $repo $rel))){throw "Broken install path: $rel"}};Write-Host 'MANIFEST_PATHS_OK'
$tmp=Join-Path ([IO.Path]::GetTempPath()) ('s8-tests-'+[guid]::NewGuid());$pkgRoot=Join-Path $tmp 'packages';$bin=Join-Path $tmp 'bin';New-Item -ItemType Directory $pkgRoot,$bin -Force|Out-Null
foreach($n in $targets){& (Join-Path $repo "tools/s8/packages/$n/install.ps1") -PackageRoot $pkgRoot -BinPath $bin;if(-not(Test-Path (Join-Path $pkgRoot $n))){throw "Install failed: $n"}};Write-Host 'CLEAN_INSTALL_OK'
$cases=@(@('m365-license-optimizer','license-optimizer.ps1','s8license','tenant.json'),@('m365-sharepoint-modernizer','sharepoint-modernizer.ps1','s8spmodern','tenant.json'),@('m365-security-baseline','security-baseline.ps1','s8baseline','tenant.json'))
foreach($c in $cases){$script=Join-Path $pkgRoot "$($c[0])/$($c[1])";$help=& $script help;if(-not($help -match $c[2])){throw "Help failed: $($c[0])"};$out=Join-Path $tmp "$($c[0])-out";& $script full -FixturePath (Join-Path $pkgRoot "$($c[0])/fixtures/$($c[3])") -OutputPath $out|Out-Null;foreach($f in @('index.html','manifest.json','collection-evidence.json')){if(-not(Test-Path (Join-Path $out $f))){throw "Report missing $f for $($c[0])"}}};Write-Host 'HELP_AND_FIXTURE_REPORTS_OK'
$diffScript=Join-Path $pkgRoot 'm365-tenant-diff/tenant-diff.ps1';$base=Join-Path $tmp 'base';$current=Join-Path $tmp 'current';& $diffScript capture -FixturePath (Join-Path $pkgRoot 'm365-tenant-diff/fixtures/tenant.json') -OutputPath $base|Out-Null;Copy-Item (Join-Path $base 'tenant-snapshot.json') (Join-Path $tmp 'current.json');$data=Get-Content (Join-Path $tmp 'current.json') -Raw|ConvertFrom-Json;$data[0].Fingerprint='changed';$data|ConvertTo-Json -Depth 30|Set-Content (Join-Path $tmp 'current.json');& $diffScript compare -BaselinePath (Join-Path $base 'tenant-snapshot.json') -CurrentPath (Join-Path $tmp 'current.json') -OutputPath $current|Out-Null;if(-not(Test-Path (Join-Path $current 'tenant-diff.json'))){throw'Tenant diff report missing'};Write-Host 'TENANT_DIFF_FIXTURE_OK'
$mig=Join-Path $pkgRoot 'm365-migration-estimator/migration-estimator.ps1';$help=& $mig help;if(-not($help-match's8migrate')){throw'Migration help failed'};$mout=Join-Path $tmp 'migration-out';& $mig estimate -InputPath (Join-Path $pkgRoot 'm365-migration-estimator/fixtures/migration.csv') -OutputPath $mout -HourlyRate 175|Out-Null;if(-not(Test-Path (Join-Path $mout 'migration-summary.json'))){throw'Migration report missing'};Write-Host 'MIGRATION_FIXTURE_OK'
Write-Host "ALL_TESTS_PASSED temp=$tmp"
