[CmdletBinding()]
param([Parameter(Position=0)][ValidateSet('assess','sites','lists','plan','full','doctor')][string]$Command='full',[string]$OutputPath=(Join-Path $PWD ('s8-sharepoint-modernizer-'+(Get-Date -Format 'yyyyMMdd-HHmmss'))),[int]$StaleDays=365,[int]$LargeListThreshold=5000,[int]$MaxSites=0,[switch]$InstallDependencies)
$modulePath=Join-Path $PSScriptRoot 'S8.M365.psm1';if(-not(Test-Path $modulePath)){$modulePath=Join-Path (Split-Path $PSScriptRoot) '_shared\S8.M365.psm1'};Import-Module $modulePath -Force;Initialize-S8Runtime
if($Command-eq'doctor'){[pscustomobject]@{PowerShell=$PSVersionTable.PSVersion.ToString();GraphModule=[bool](Get-Module -ListAvailable Microsoft.Graph.Authentication);LargeListThreshold=$LargeListThreshold;OutputPath=$OutputPath}|Format-List;exit}
$evidence=New-Object System.Collections.ArrayList;$context=Connect-S8Graph @('Sites.Read.All','Directory.Read.All') -InstallDependencies:$InstallDependencies
$sites=Invoke-S8Collection 'SharePoint sites' {Get-S8GraphCollection 'https://graph.microsoft.com/v1.0/sites?search=*&$select=id,displayName,name,webUrl,createdDateTime,lastModifiedDateTime,siteCollection'} $evidence
if($MaxSites-gt 0){$sites=@($sites|Select-Object -First $MaxSites)}
$siteRows=@();$listRows=@();foreach($site in $sites){$lists=Invoke-S8Collection "Lists: $($site.webUrl)" {Get-S8GraphCollection "https://graph.microsoft.com/v1.0/sites/$($site.id)/lists?`$select=id,displayName,webUrl,createdDateTime,lastModifiedDateTime,list,system"} $evidence;$large=0;foreach($list in $lists){$count=$null;try{$drive=Invoke-MgGraphRequest GET "https://graph.microsoft.com/v1.0/sites/$($site.id)/lists/$($list.id)/drive?`$select=id,quota" -OutputType PSObject;$count=$drive.quota.used}catch{};if($count-ge$LargeListThreshold){$large++};$listRows+=[pscustomobject]@{Site=$site.webUrl;List=$list.displayName;Template=$list.list.template;Created=$list.createdDateTime;Modified=$list.lastModifiedDateTime;EstimatedItems=$count;Large=[bool]($count-ge$LargeListThreshold);System=[bool]$list.system}}
 $days=if($site.lastModifiedDateTime){[math]::Floor(((Get-Date)-[datetime]$site.lastModifiedDateTime).TotalDays)}else{$null};$flags=@();if($days-ge$StaleDays){$flags+='Stale site'};if($large){$flags+="$large large libraries"};if($site.webUrl-match'/sites/[^/]+/'){ $flags+='Review nested/legacy URL structure' }
 $siteRows+=[pscustomobject]@{Site=$site.displayName;Url=$site.webUrl;Created=$site.createdDateTime;Modified=$site.lastModifiedDateTime;DaysSinceModified=$days;Lists=$lists.Count;LargeLists=$large;Personal=[bool]($site.webUrl-match'-my\.sharepoint\.com/personal/');ModernizationFlags=($flags-join'; ');Priority=if($large){'High'}elseif($days-ge$StaleDays){'Medium'}else{'Low'}}}
$plan=@($siteRows|Where-Object ModernizationFlags|ForEach-Object{[pscustomobject]@{Priority=$_.Priority;Site=$_.Site;Url=$_.Url;Finding=$_.ModernizationFlags;RecommendedAction=if($_.LargeLists){'Inventory library scale, indexing, views and migration constraints'}else{'Confirm ownership, business value and archive or modernization path'};ChangeMode='Plan only - no tenant changes'}})
New-Item -ItemType Directory $OutputPath -Force|Out-Null;Export-S8Data $OutputPath 'site-assessment' $siteRows;Export-S8Data $OutputPath 'list-assessment' $listRows;Export-S8Data $OutputPath 'modernization-plan' $plan;Complete-S8Run $OutputPath 'm365-sharepoint-modernizer' $Command $context $evidence;Write-S8Report $OutputPath 'System 8 · SharePoint Modernizer' ([ordered]@{'Modernization plan'=$plan;'Sites'=$siteRows;'Lists and libraries'=$listRows;'Collection evidence'=@($evidence)})
[pscustomobject]@{Output=$OutputPath;Sites=$siteRows.Count;Lists=$listRows.Count;PlanItems=$plan.Count;Mode='Read-only discovery and planning'}|Format-List
