[CmdletBinding()]
param([Parameter(Position=0)][ValidateSet('assess','plan','doctor')][string]$Command='assess',[string]$UserPrincipalName,[string]$OutputPath=(Join-Path $PWD ('s8-leaver-'+(Get-Date -Format 'yyyyMMdd-HHmmss'))),[switch]$InstallDependencies)
$modulePath=Join-Path $PSScriptRoot 'S8.M365.psm1';if(-not(Test-Path $modulePath)){$modulePath=Join-Path (Split-Path $PSScriptRoot) '_shared\S8.M365.psm1'};Import-Module $modulePath -Force;Initialize-S8Runtime
if($Command-eq'doctor'){[pscustomobject]@{PowerShell=$PSVersionTable.PSVersion.ToString();GraphModule=[bool](Get-Module -ListAvailable Microsoft.Graph.Authentication);OutputPath=$OutputPath}|Format-List;exit};if(-not$UserPrincipalName){throw 'assess requires -UserPrincipalName.'}
$evidence=New-Object System.Collections.ArrayList;$context=Connect-S8Graph @('User.Read.All','Group.Read.All','Directory.Read.All','Application.Read.All','Files.Read.All','LicenseAssignment.Read.All') -InstallDependencies:$InstallDependencies;$escaped=[uri]::EscapeDataString($UserPrincipalName)
$user=@(Invoke-S8Collection 'User' {Get-S8GraphCollection "https://graph.microsoft.com/v1.0/users/$escaped?`$select=id,displayName,userPrincipalName,accountEnabled,userType,assignedLicenses,createdDateTime"} $evidence)|Select-Object -First 1;if(-not$user){throw "User not found: $UserPrincipalName"};$id=$user.id
$owned=Invoke-S8Collection 'Owned directory objects' {Get-S8GraphCollection "https://graph.microsoft.com/v1.0/users/$id/ownedObjects?`$select=id,displayName,appId,groupTypes,resourceProvisioningOptions"} $evidence;$memberships=Invoke-S8Collection 'Transitive memberships' {Get-S8GraphCollection "https://graph.microsoft.com/v1.0/users/$id/transitiveMemberOf?`$select=id,displayName,groupTypes,resourceProvisioningOptions"} $evidence;$reports=Invoke-S8Collection 'Direct reports' {Get-S8GraphCollection "https://graph.microsoft.com/v1.0/users/$id/directReports?`$select=id,displayName,userPrincipalName"} $evidence;$manager=Invoke-S8Collection 'Manager' {Get-S8GraphCollection "https://graph.microsoft.com/v1.0/users/$id/manager?`$select=id,displayName,userPrincipalName"} $evidence;$drive=Invoke-S8Collection 'OneDrive metadata' {Get-S8GraphCollection "https://graph.microsoft.com/v1.0/users/$id/drive?`$select=id,name,webUrl,driveType,quota"} $evidence
$dependencies=@();foreach($x in $owned){$dependencies+=[pscustomobject]@{Area='Ownership';Dependency=$x.displayName;ObjectId=$x.id;Risk='Transfer ownership before account disablement';Evidence=$x.'@odata.type'}};foreach($x in $reports){$dependencies+=[pscustomobject]@{Area='People';Dependency=$x.displayName;ObjectId=$x.id;Risk='Reassign manager';Evidence=$x.userPrincipalName}};foreach($x in $drive){$dependencies+=[pscustomobject]@{Area='OneDrive';Dependency=$x.webUrl;ObjectId=$x.id;Risk='Confirm retention, transfer and legal requirements';Evidence="Used=$($x.quota.used); Total=$($x.quota.total)"}}
$plan=@([pscustomobject]@{Sequence=10;Action='Confirm HR/legal authorization and effective time';Mode='Manual approval';EvidenceRequired='Ticket or approved leaver record'},[pscustomobject]@{Sequence=20;Action='Transfer owned groups, Teams, applications and service principals';Mode='Plan only';EvidenceRequired="$(@($owned).Count) owned objects"},[pscustomobject]@{Sequence=30;Action='Reassign direct reports and operational responsibilities';Mode='Plan only';EvidenceRequired="$(@($reports).Count) direct reports"},[pscustomobject]@{Sequence=40;Action='Preserve mailbox, OneDrive and records according to policy';Mode='Plan only';EvidenceRequired="$(@($drive).Count) OneDrive records; Exchange/Purview evidence external"},[pscustomobject]@{Sequence=50;Action='Block sign-in, revoke sessions and remove licences only in approved change window';Mode='Not executed';EvidenceRequired='Separate write-authorized runbook'},[pscustomobject]@{Sequence=60;Action='Validate residual access, forwarding, delegation and automation ownership';Mode='Manual validation';EvidenceRequired='Exchange, Teams, SharePoint and application evidence'})
New-Item -ItemType Directory $OutputPath -Force|Out-Null;Export-S8Data $OutputPath 'leaver-identity' @($user);Export-S8Data $OutputPath 'leaver-dependencies' $dependencies;Export-S8Data $OutputPath 'leaver-plan' $plan;Export-S8Data $OutputPath 'memberships-evidence' $memberships;Export-S8Data $OutputPath 'manager-evidence' $manager;Complete-S8Run $OutputPath 'm365-leaver-readiness' $Command $context $evidence;Write-S8Report $OutputPath 'System 8 · M365 Leaver Readiness' ([ordered]@{'Leaver plan'=$plan;'Dependencies'=$dependencies;'Membership evidence'=$memberships;'Collection evidence'=@($evidence)})
[pscustomobject]@{Output=$OutputPath;Identity=$UserPrincipalName;Dependencies=$dependencies.Count;Mode='Read-only dependency discovery; no offboarding actions executed'}|Format-List
