[CmdletBinding()]
param([Parameter(Position=0)][ValidateSet('health','changes','impact','full','doctor')][string]$Command='full',[string]$OutputPath=(Join-Path $PWD ('s8-change-impact-'+(Get-Date -Format 'yyyyMMdd-HHmmss'))),[int]$LookAheadDays=90,[switch]$InstallDependencies)
$modulePath=Join-Path $PSScriptRoot 'S8.M365.psm1';if(-not(Test-Path $modulePath)){$modulePath=Join-Path (Split-Path $PSScriptRoot) '_shared\S8.M365.psm1'};Import-Module $modulePath -Force;Initialize-S8Runtime
if($Command-eq'doctor'){[pscustomobject]@{PowerShell=$PSVersionTable.PSVersion.ToString();GraphModule=[bool](Get-Module -ListAvailable Microsoft.Graph.Authentication);LookAheadDays=$LookAheadDays;OutputPath=$OutputPath}|Format-List;exit}
$evidence=New-Object System.Collections.ArrayList;$context=Connect-S8Graph @('ServiceMessage.Read.All','Organization.Read.All','User.Read.All','Group.Read.All','Sites.Read.All') -InstallDependencies:$InstallDependencies
$health=Invoke-S8Collection 'Service health' {Get-S8GraphCollection 'https://graph.microsoft.com/v1.0/admin/serviceAnnouncement/healthOverviews?$expand=issues'} $evidence
$messages=Invoke-S8Collection 'Message Center' {Get-S8GraphCollection 'https://graph.microsoft.com/v1.0/admin/serviceAnnouncement/messages?$top=999'} $evidence
$users=Invoke-S8Collection 'User scale' {Get-S8GraphCollection 'https://graph.microsoft.com/v1.0/users?$select=id,accountEnabled'} $evidence;$groups=Invoke-S8Collection 'Group scale' {Get-S8GraphCollection 'https://graph.microsoft.com/v1.0/groups?$select=id,groupTypes,resourceProvisioningOptions'} $evidence;$sites=Invoke-S8Collection 'Site scale' {Get-S8GraphCollection 'https://graph.microsoft.com/v1.0/sites?search=*&$select=id,webUrl'} $evidence
$healthRows=@();foreach($service in $health){foreach($issue in @($service.issues)){$healthRows+=[pscustomobject]@{Service=$service.service;Status=$service.status;IssueId=$issue.id;Title=$issue.title;Classification=$issue.classification;Origin=$issue.origin;Start=$issue.startDateTime;End=$issue.endDateTime;ImpactDescription=$issue.impactDescription}};if(-not$service.issues){$healthRows+=[pscustomobject]@{Service=$service.service;Status=$service.status;IssueId=$null;Title=$null;Classification=$null;Origin=$null;Start=$null;End=$null;ImpactDescription=$null}}}
$cut=(Get-Date).AddDays($LookAheadDays);$changeRows=@($messages|ForEach-Object{$deadline=$_.actionRequiredByDateTime;if(-not$deadline){$deadline=$_.endDateTime};[pscustomobject]@{Id=$_.id;Title=$_.title;Category=$_.category;Severity=$_.severity;Services=(@($_.services)-join';');Start=$_.startDateTime;Deadline=$deadline;ActionRequiredBy=$_.actionRequiredByDateTime;IsMajorChange=$_.isMajorChange;State=$_.state;Tags=(@($_.tags)-join';');WithinLookAhead=[bool]($deadline-and([datetime]$deadline-le$cut));Body=$_.body.content}})
$enabledUsers=@($users|Where-Object accountEnabled).Count;$teams=@($groups|Where-Object{$_.resourceProvisioningOptions-contains'Team'}).Count
$impact=@($changeRows|Where-Object{$_.IsMajorChange-or$_.ActionRequiredBy}|ForEach-Object{
 $services=$_.Services
 if($services-match'Teams'){$scale=$teams}elseif($services-match'SharePoint|OneDrive'){$scale=$sites.Count}else{$scale=$enabledUsers}
 if($_.ActionRequiredBy-and([datetime]$_.ActionRequiredBy-lt(Get-Date).AddDays(30))){$urgency=3}elseif($_.IsMajorChange){$urgency=2}else{$urgency=1}
 $action=if($_.ActionRequiredBy){'Assign owner and decision before action-required date'}else{'Assess, communicate, test and record disposition'}
 [pscustomobject]@{Id=$_.Id;Title=$_.Title;Services=$services;Deadline=$_.Deadline;AffectedScale=$scale;ImpactScore=[math]::Min(100,[math]::Round($urgency*20+[math]::Log10([math]::Max(1,$scale))*10));OperatorAction=$action;Evidence='Message Center + live tenant scale'}
}|Sort-Object ImpactScore -Descending)
New-Item -ItemType Directory $OutputPath -Force|Out-Null;Export-S8Data $OutputPath 'service-health' $healthRows;Export-S8Data $OutputPath 'message-center' $changeRows;Export-S8Data $OutputPath 'change-impact-register' $impact;Complete-S8Run $OutputPath 'm365-change-impact' $Command $context $evidence;Write-S8Report $OutputPath 'System 8 · M365 Change Impact' ([ordered]@{'Prioritized change register'=$impact;'Service health'=$healthRows;'Message Center'=$changeRows;'Collection evidence'=@($evidence)})
[pscustomobject]@{Output=$OutputPath;HealthIssues=@($healthRows|Where-Object IssueId).Count;Messages=$changeRows.Count;PrioritizedChanges=$impact.Count;Mode='Read-only operational triage'}|Format-List
