[CmdletBinding()]
param([Parameter(Position=0)][ValidateSet('template','assess','catalog','doctor')][string]$Command='assess',[string]$RequirementsPath,[string]$OutputPath=(Join-Path $PWD ('s8-entitlement-'+(Get-Date -Format 'yyyyMMdd-HHmmss'))),[switch]$InstallDependencies)
$modulePath=Join-Path $PSScriptRoot 'S8.M365.psm1';if(-not(Test-Path $modulePath)){$modulePath=Join-Path (Split-Path $PSScriptRoot) '_shared\S8.M365.psm1'};Import-Module $modulePath -Force;Initialize-S8Runtime
if($Command-eq'doctor'){[pscustomobject]@{PowerShell=$PSVersionTable.PSVersion.ToString();GraphModule=[bool](Get-Module -ListAvailable Microsoft.Graph.Authentication);RequirementsPath=$RequirementsPath;OutputPath=$OutputPath}|Format-List;exit}
New-Item -ItemType Directory $OutputPath -Force|Out-Null
if($Command-eq'template'){@([pscustomobject]@{Persona='Information Worker';Capability='Office desktop apps';RequiredServicePlans='OFFICESUBSCRIPTION'},[pscustomobject]@{Persona='Security Administrator';Capability='Entra ID P1 controls';RequiredServicePlans='AAD_PREMIUM'},[pscustomobject]@{Persona='Copilot Pilot';Capability='Microsoft 365 Copilot';RequiredServicePlans='M365_COPILOT'})|Export-Csv (Join-Path $OutputPath 'requirements-template.csv') -NoTypeInformation -Encoding UTF8;Write-Host "Template: $(Join-Path $OutputPath 'requirements-template.csv')";exit}
$evidence=New-Object System.Collections.ArrayList;$context=Connect-S8Graph @('User.Read.All','Organization.Read.All','Directory.Read.All') -InstallDependencies:$InstallDependencies
$skus=Invoke-S8Collection 'Subscribed SKUs and service plans' {Get-S8GraphCollection 'https://graph.microsoft.com/v1.0/subscribedSkus'} $evidence
$users=Invoke-S8Collection 'Users and assigned plans' {Get-S8GraphCollection 'https://graph.microsoft.com/v1.0/users?$select=id,displayName,userPrincipalName,accountEnabled,userType,assignedLicenses,assignedPlans'} $evidence
$planMap=@{};$catalog=@();foreach($sku in $skus){foreach($plan in @($sku.servicePlans)){$planMap[[string]$plan.servicePlanId]=$plan.servicePlanName;$catalog+=[pscustomobject]@{SkuPartNumber=$sku.skuPartNumber;SkuId=$sku.skuId;ServicePlanName=$plan.servicePlanName;ServicePlanId=$plan.servicePlanId;AppliesTo=$plan.appliesTo;ProvisioningStatus=$plan.provisioningStatus}}}
Export-S8Data $OutputPath 'tenant-entitlement-catalog' $catalog
if($Command-eq'catalog'){Complete-S8Run $OutputPath 'm365-entitlement-advisor' $Command $context $evidence;Write-S8Report $OutputPath 'System 8 · Tenant Entitlement Catalog' ([ordered]@{'Tenant service plans'=$catalog;'Collection evidence'=@($evidence)});exit}
if(-not$RequirementsPath){throw 'assess requires -RequirementsPath. Run template to create a requirements CSV.'};$requirements=@(Import-Csv $RequirementsPath)
$rows=@();foreach($user in $users){$enabledPlans=@($user.assignedPlans|Where-Object capabilityStatus-eq'Enabled'|ForEach-Object{$planMap[[string]$_.servicePlanId]});foreach($requirement in $requirements){$needed=@($requirement.RequiredServicePlans-split';'|Where-Object{$_});$missing=@($needed|Where-Object{$_-notin$enabledPlans});$rows+=[pscustomobject]@{UPN=$user.userPrincipalName;DisplayName=$user.displayName;AccountEnabled=$user.accountEnabled;Persona=$requirement.Persona;Capability=$requirement.Capability;RequiredPlans=($needed-join';');MissingPlans=($missing-join';');Status=if(-not$user.accountEnabled){'NotApplicable-Disabled'}elseif($missing.Count){'Gap'}else{'Covered'};EvidenceSource='Live assignedPlans + operator requirements'}}}
$gaps=@($rows|Where-Object Status-eq'Gap');Export-S8Data $OutputPath 'user-capability-assessment' $rows;Export-S8Data $OutputPath 'entitlement-gaps' $gaps;Export-S8Data $OutputPath 'requirements-evidence' $requirements;Complete-S8Run $OutputPath 'm365-entitlement-advisor' $Command $context $evidence;Write-S8Report $OutputPath 'System 8 · M365 Entitlement Advisor' ([ordered]@{'Entitlement gaps'=$gaps;'User capability assessment'=$rows;'Tenant service plan catalog'=$catalog;'Collection evidence'=@($evidence)})
[pscustomobject]@{Output=$OutputPath;Users=$users.Count;Requirements=$requirements.Count;Gaps=$gaps.Count;Mode='Read-only; operator-supplied capability requirements'}|Format-List
