[CmdletBinding()]
param([Parameter(Position=0)][ValidateSet('assess','identity','apps','access','full','doctor')][string]$Command='full',[string]$OutputPath=(Join-Path $PWD ('s8-security-baseline-'+(Get-Date -Format 'yyyyMMdd-HHmmss'))),[switch]$InstallDependencies)
$modulePath=Join-Path $PSScriptRoot 'S8.M365.psm1';if(-not(Test-Path $modulePath)){$modulePath=Join-Path (Split-Path $PSScriptRoot) '_shared\S8.M365.psm1'};Import-Module $modulePath -Force;Initialize-S8Runtime
if($Command-eq'doctor'){[pscustomobject]@{PowerShell=$PSVersionTable.PSVersion.ToString();GraphModule=[bool](Get-Module -ListAvailable Microsoft.Graph.Authentication);OutputPath=$OutputPath}|Format-List;exit}
$evidence=New-Object System.Collections.ArrayList;$context=Connect-S8Graph @('Directory.Read.All','Policy.Read.All','Application.Read.All','AuditLog.Read.All','Organization.Read.All') -InstallDependencies:$InstallDependencies
$ca=Invoke-S8Collection 'Conditional Access policies' {Get-S8GraphCollection 'https://graph.microsoft.com/v1.0/identity/conditionalAccess/policies'} $evidence
$roles=Invoke-S8Collection 'Directory roles' {Get-S8GraphCollection 'https://graph.microsoft.com/v1.0/directoryRoles?$expand=members'} $evidence
$apps=Invoke-S8Collection 'Service principals' {Get-S8GraphCollection 'https://graph.microsoft.com/v1.0/servicePrincipals?$select=id,appId,displayName,accountEnabled,servicePrincipalType,publisherName,verifiedPublisher,passwordCredentials,keyCredentials'} $evidence
$auth=Invoke-S8Collection 'Authorization policy' {Get-S8GraphCollection 'https://graph.microsoft.com/v1.0/policies/authorizationPolicy'} $evidence
$findings=@()
function Add-Finding($id,$area,$severity,$status,$evidenceText,$recommendation){$script:findings+=[pscustomobject]@{Id=$id;Area=$area;Severity=$severity;Status=$status;Evidence=$evidenceText;Recommendation=$recommendation;ChangeMode='Advisory only'}}
$enabled=@($ca|Where-Object state-eq'enabled');$mfa=@($enabled|Where-Object{$_.grantControls.builtInControls-contains'mfa'});$block=@($enabled|Where-Object{$_.grantControls.builtInControls-contains'block'})
Add-Finding 'CA-001' 'Conditional Access' 'High' $(if($enabled.Count){'Pass'}else{'Fail'}) "$($enabled.Count) enabled policies" 'Maintain enabled Conditional Access coverage with tested emergency access exclusions.'
Add-Finding 'CA-002' 'Conditional Access' 'High' $(if($mfa.Count){'Pass'}else{'Review'}) "$($mfa.Count) enabled policies require MFA" 'Require phishing-resistant MFA for privileged and high-risk access where licensing permits.'
Add-Finding 'CA-003' 'Conditional Access' 'High' $(if($block.Count){'Pass'}else{'Review'}) "$($block.Count) enabled blocking policies" 'Review legacy authentication and unacceptable risk blocking coverage.'
$admins=@();foreach($r in $roles){foreach($m in @($r.members)){$admins+=[pscustomobject]@{Role=$r.displayName;Member=$m.displayName;UPN=$m.userPrincipalName;Type=$m.'@odata.type'}}};$ga=@($admins|Where-Object Role-eq'Global Administrator')
Add-Finding 'ID-001' 'Privileged identity' 'Medium' $(if($ga.Count-ge2-and$ga.Count-le4){'Pass'}else{'Review'}) "$($ga.Count) Global Administrators" 'Keep a small, resilient Global Administrator set and use least-privilege roles.'
$unverified=@($apps|Where-Object{$_.servicePrincipalType-eq'Application'-and-not$_.verifiedPublisher.verifiedPublisherId});$expiring=@($apps|Where-Object{@($_.passwordCredentials|Where-Object{[datetime]$_.endDateTime-lt(Get-Date).AddDays(90)}).Count})
Add-Finding 'APP-001' 'Applications' 'Medium' $(if($unverified.Count){'Review'}else{'Pass'}) "$($unverified.Count) unverified publisher applications" 'Validate publisher, ownership, consent and business need.'
Add-Finding 'APP-002' 'Applications' 'High' $(if($expiring.Count){'Review'}else{'Pass'}) "$($expiring.Count) applications have expired or near-expiry secrets" 'Rotate credentials and prefer certificates or workload identity federation.'
$appRows=@($apps|ForEach-Object{[pscustomobject]@{Name=$_.displayName;AppId=$_.appId;Enabled=$_.accountEnabled;Publisher=$_.publisherName;VerifiedPublisher=$_.verifiedPublisher.verifiedPublisherId;Secrets=@($_.passwordCredentials).Count;Certificates=@($_.keyCredentials).Count}})
New-Item -ItemType Directory $OutputPath -Force|Out-Null;Export-S8Data $OutputPath 'baseline-findings' $findings;Export-S8Data $OutputPath 'privileged-role-members' $admins;Export-S8Data $OutputPath 'applications' $appRows;Export-S8Data $OutputPath 'conditional-access-policies' $ca;Export-S8Data $OutputPath 'authorization-policy' $auth;Complete-S8Run $OutputPath 'm365-security-baseline' $Command $context $evidence;Write-S8Report $OutputPath 'System 8 · M365 Security Baseline' ([ordered]@{'Baseline findings'=$findings;'Privileged roles'=$admins;'Applications'=$appRows;'Collection evidence'=@($evidence)})
[pscustomobject]@{Output=$OutputPath;Findings=$findings.Count;Failed=@($findings|Where-Object Status-eq'Fail').Count;Review=@($findings|Where-Object Status-eq'Review').Count;Mode='Read-only assessment'}|Format-List
